apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore
  annotations:
    sidecar.speedscale.com/inject: "true"
    #sidecar.speedscale.com/tls-out: "true"
spec:
  selector:
    matchLabels:
      app: jpetstore
  template:
    metadata:
      labels:
        app: jpetstore
    spec:
      containers:
      - name: jpetstore
        image: 192.168.1.40:5200/my-jpetstore:latest
        env:
        - name: DATABASE_HOST
          value: mysql
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: jpetstore
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: yourpassword
        #- name: JAVA_OPTS
          #value: >-
          #    -Djavax.net.ssl.trustStore=/etc/ssl/speedscale/jks/cacerts.jks
          #    -Djavax.net.ssl.trustStorePassword=changeit
        ports:
        - containerPort: 8080
